version: 2.1

executors:
  ubuntu:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:15.0.2
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

commands:
  read_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
  write_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  linux-build:
    executor: ubuntu
    steps:
      - checkout
      - read_cache
      - run:
          name: "Run tests"
          command: ./gradlew iTest
      - run:
          name: "Create Package deb"
          command: ./gradlew packageDeb
      - write_cache
      - store_test_results:
          path: ~/repo/build/test-results/iTest/
      - run:
          name: "Store deb to workspace"
          command: mkdir -p artifacts; cp ~/repo/build/compose/binaries/main/deb/* artifacts/
      - persist_to_workspace:
          root: artifacts
          paths:
            - .
      - store_artifacts:
          path: artifacts/

  mac-build:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - attach_workspace:
            at: artifacts
      - run: brew tap adoptopenjdk/openjdk
      - run: brew install adoptopenjdk15
      - run: echo 'export PATH="/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home/bin:$PATH"' >> ~/.zshrc
      - run: source ~/.zshrc
      - run:
          name: "Create DMG"
          command: ./gradlew packageDmg
      - run:
          name: "Store dmg to workspace"
          command: cp ~/repo/build/compose/binaries/main/dmg/* artifacts/
      - run:
          name: "Notarize DMG"
          command: ./gradlew notarizeDmg
      - persist_to_workspace:
          root: artifacts
          paths:
            - .
      - store_artifacts:
          path: artifacts/

  publish-github-release:
    docker:
      - image: cibuilds/github
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2.1
  all-os-build:
    jobs:
      - linux-build:
          filters:
            tags:
              only: /.*/ # Runs on every branch and tag
      - mac-build:
          requires:
            - linux-build
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - mac-build
          filters:
            branches:
              ignore: /.*/ # Does not publish on any branch, tags only
            tags:
              only: /^\d+\.\d+\.\d+$/ # Only publishes on tags with this format: 1.2.3
