# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  linux-build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:15.0.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: ./gradlew iTest
      - store_test_results:
          path: ~/repo/build/reports/tests/iTest/index.html

workflows:
  version: 2
  all-os-build:
    jobs:
      - linux-build
