version: 2.1

executors:
  ubuntu:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:15.0.2
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

commands:
  read_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

  write_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  linux-build:
    executor: ubuntu
    steps:
      - checkout
      - read_cache

      - run:
          name: "Run tests"
          command: ./gradlew iTest

      - run:
          name: "Create Package deb"
          command: ./gradlew packageDeb

      - write_cache

      - store_test_results:
          path: ~/repo/build/test-results/iTest/
      - store_artifacts:
          path: ~/repo/build/compose/binaries/main/deb/

workflows:
  version: 2.1
  all-os-build:
    jobs:
      - linux-build
